import { FileText, ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router";

const LAST_UPDATED = "17 March 2026";
const COMPANY = "InternIQ";
const EMAIL = "hello@interniq.co.uk";
const WEBSITE = "interniq.co.uk";

export default function TermsPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate("/")}>
            <FileText className="w-6 h-6" />
            <span className="text-xl tracking-tight">{COMPANY}</span>
          </div>
          <button
            onClick={() => navigate(-1)}
            className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors text-sm"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-10">
          <h1 className="text-4xl font-medium mb-3">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed">

          <Section title="1. Acceptance of terms">
            <p>
              By accessing or using {WEBSITE} ("the Service"), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </Section>

          <Section title="2. Description of service">
            <p>
              {COMPANY} provides an AI-powered CV analysis tool that reviews uploaded CVs against
              job descriptions and provides feedback including ATS scores, keyword analysis, and
              improvement suggestions. The Service is intended for personal, non-commercial use by
              internship and job applicants.
            </p>
          </Section>

          <Section title="3. Acceptable use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Upload files that are not genuine CVs (malware, exploits, or other harmful content)</li>
              <li>Attempt to circumvent rate limits or access controls</li>
              <li>Use automated scripts or bots to access the Service</li>
              <li>Upload CVs belonging to other people without their consent</li>
              <li>Use the Service in any way that violates applicable UK law</li>
              <li>Attempt to extract, reverse-engineer, or replicate our AI prompts or models</li>
            </ul>
          </Section>

          <Section title="4. CV data and privacy">
            <p>
              We take your privacy seriously. Your CV is processed entirely in memory and is
              <strong> never stored on our servers</strong>. The text is sent to our AI provider
              (Anthropic) for analysis and deleted immediately afterwards. By uploading a CV, you
              confirm you have the right to share its contents and consent to this processing.
              See our <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a> for full details.
            </p>
          </Section>

          <Section title="5. AI-generated content disclaimer">
            <p>
              The analysis, scores, and suggestions provided by {COMPANY} are generated by an AI
              model and are provided for informational purposes only. They do not constitute
              professional career advice. {COMPANY} makes no guarantee that following our
              suggestions will result in a job offer, interview, or any other outcome. Always
              apply your own judgement.
            </p>
          </Section>

          <Section title="6. Intellectual property">
            <p>
              The {COMPANY} name, logo, website design, and software are the intellectual property
              of {COMPANY}. You retain all rights to your CV content. By uploading your CV, you
              grant us a limited, temporary licence to process it solely for the purpose of
              providing your analysis.
            </p>
          </Section>

          <Section title="7. Limitation of liability">
            <p>
              To the maximum extent permitted by UK law, {COMPANY} shall not be liable for any
              indirect, incidental, special, or consequential damages arising from your use of
              the Service, including but not limited to loss of employment opportunity, loss of
              data, or loss of income. Our total liability shall not exceed the amount you paid
              us in the 30 days preceding the claim.
            </p>
          </Section>

          <Section title="8. Service availability">
            <p>
              We aim to keep {COMPANY} available at all times but make no guarantee of uptime.
              We reserve the right to modify, suspend, or discontinue the Service at any time
              with reasonable notice where possible.
            </p>
          </Section>

          <Section title="9. Changes to these terms">
            <p>
              We may update these terms from time to time. Continued use of the Service after
              changes constitutes acceptance of the updated terms. Material changes will be
              communicated via email to registered users.
            </p>
          </Section>

          <Section title="10. Governing law">
            <p>
              These terms are governed by the laws of England and Wales. Any disputes shall be
              subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </Section>

          <Section title="11. Contact">
            <p>
              For any questions about these terms, contact us at:{" "}
              <a href={`mailto:${EMAIL}`} className="text-primary hover:underline">{EMAIL}</a>
            </p>
          </Section>

        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-medium mb-3">{title}</h2>
      <div className="text-muted-foreground space-y-2">{children}</div>
    </section>
  );
}
